server:
  port: 8081

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      enabled: true
      connect-string: localhost:2281
      discovery:
        root: /spring-cloud/service

