server:
  port: 8084

spring:
  application:
    name: cloud-consumer-order-hystrix

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        #feign超时时间
        connectTimeout: 5000
        readTimeout: 3000


logging:
  level:
    com.bandit.springCloud.service.PaymentService: debug
