server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-cloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bandit.springCloud.entities


eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    #表示注册自己进EurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息。单点无所谓，集群必须要true
    fetch-registry: true
    service-url:
      # 单机版
      #defaultZone: http://localhost:7001/eureka/
      # 集群版
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
