server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route
          uri: lb://CLOUD-PROVIDER-PAYMENT #lb://  loadBalance 自动负载均衡选择服务名 动态路由
          predicates:
            # Cookie：key, value
            - Cookie=mycookie,a*
            - Path=/payment/*
            - After=2022-04-25T14:36:47.141+08:00[Asia/Shanghai]
            - Method=GET,POST
          filters:
            - AddRequestHeader=X-Request-red, blue


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


